name: MiniBosses
main: MiniBosses\Main
description: Adds very customisable Bosses
version: 2.0.0
api: 3.14.2
load: POSTWORLD
author: ace
commands:
  minibosses:
    description: Manage MiniBosses
    usage: "/minibosses <create/spawn/delete/list>"
    permission: minibosses.command
permissions:
  minibosses.command:
    description: "Allows usage of the minibosses command."
    default: op
